In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.21.0'

In [4]:
dataset=pd.read_csv(r'F:\FSDS Work\DL\Churn_Modelling.csv')

In [5]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [6]:
dataset

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,delhi,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,delhi,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,delhi,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,mumbai,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,delhi,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
X

array([[619, 'delhi', 'Female', ..., 1, 1, 101348.88],
       [608, 'bangalore', 'Female', ..., 0, 1, 112542.58],
       [502, 'delhi', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 'Female', ..., 0, 1, 42085.58],
       [772, 'mumbai', 'Male', ..., 1, 0, 92888.52],
       [792, 'delhi', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [9]:
dataset.head(3)

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [11]:
X

array([[619, 'delhi', 0, ..., 1, 1, 101348.88],
       [608, 'bangalore', 0, ..., 0, 1, 112542.58],
       [502, 'delhi', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 0, ..., 0, 1, 42085.58],
       [772, 'mumbai', 1, ..., 1, 0, 92888.52],
       [792, 'delhi', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [13]:
X

array([[0.0, 1.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [15]:
X

array([[-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.74273971, -1.00280393, -0.57873591, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.57380915,  0.99720391, -0.57873591, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-0.57380915, -1.00280393,  1.72790383, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)

# ANN Model Building Architecture

In [18]:
ann=tf.keras.models.Sequential()

In [19]:
ann.add(tf.keras.layers.Dense(units=6))

In [20]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units=4,activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [24]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [25]:
ann.fit(X_train,y_train,batch_size=32,epochs=20)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.7358 - loss: 0.5630
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7964 - loss: 0.4589
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8033 - loss: 0.4336
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8004 - loss: 0.4288
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8005 - loss: 0.4272
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8043 - loss: 0.4253
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8049 - loss: 0.4234
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8109 - loss: 0.4202
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8179 - loss: 0.4131
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8271 - loss: 0.3984
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8409 - loss: 0.3745
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8547 - loss: 0.3568
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8566 - loss: 0.3500
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8591 - loss: 0.3465
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8591 - loss: 0.3448
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - loss: 0.3445
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8604 - loss: 0.3432
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8604 - loss: 0.3428
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8601 - loss: 0.3419
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8604 - loss: 0.3418

In [26]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1539   56]
 [ 216  189]]

In [29]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
print(ac)

0.864